name: Commit Workflow

on:
  push:
  workflow_dispatch:

jobs:
  no-tty-in-ci:
    name: Ensure no TTY if user does not need to input anything
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_REPOSITORY_USERNAME: ${{ secrets.ARTIFACTS_REPOSITORY_USERNAME }}
      ARTIFACTS_REPOSITORY_PASSWORD: ${{ secrets.ARTIFACTS_REPOSITORY_PASSWORD }}
      ANSIBLE_VAULT_PW: ${{ secrets.ANSIBLE_VAULT_PW }}
      PLASMACTL_KEYRING_PASSWORD: ${{ secrets.PLASMACTL_KEYRING_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          mkdir -p .compose/build/platform/ .compose/packages/example/main
          echo -e '[local]\nlocalhost ansible_connection=local' > hosts
          echo -e '---\n- name: Echo test on local host\n  hosts: local\n  gather_facts: false\n  connection: local\n  tasks:\n    - name: Run echo command\n      ansible.builtin.shell: echo "test"' > .compose/build/platform/platform.yaml
          echo -e 'name: launchr\ndependencies:\n  - name: example\n    source:\n      type: git\n      ref: main\n      url: https://github.com/davidferlay/compose-example.git\n      strategy: null' > plasma-compose.yaml
          ./bin/launchr bump --sync --vault-pass "xxx" --keyring-passphrase "xxx" -vvv

  commands-ok:
    name: Ensure main commands do not fail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make deps build
          ls -lah bin/launchr
          mkdir -p interaction/softwares/roles/whatever/meta/
          cat <<EOF > interaction/softwares/roles/whatever/meta/plasma.yaml
          plasma:
            author: Whoever
            categories:
            - kind.software
            - machine
            description: Whatever
            license: MIT
            version: 197d7ab84a2b4
          EOF
          touch interaction/softwares/roles/whatever/meta/whatever
          cat interaction/softwares/roles/whatever/meta/whatever
          git add -A
          git config --global user.email "citesting@example.com"
          git config --global user.name "CI testing"
          git commit -m "CI testing"
          ./bin/launchr bump

  go-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make lint

  go-tests:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commands
        run: |
          set -x
          date
          pwd
          whoami
          make test

